#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u "$WWWUSER" cluebots
fi

if [ $# -gt 0 ];then
    exec gosu "$WWWUSER" "$@"
else
    if [ "$APP_ENV" = "production" ]; then
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.prod.conf
    else
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.dev.conf
    fi
fi
