#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u "$WWWUSER" cluebots
fi

if [[ "$GENERATE_SELF_SIGNED_CERTIFICATES" = true ]] && [[ ! -f "/etc/nginx/certs/$APP_DOMAIN.crt" ]] ; then
    echo "Generating ssl certificate..."
    generate-ssl-certificate;
fi

if [ $# -gt 0 ];then
    exec gosu "$WWWUSER" "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
